#!/bin/bash

cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=./ios.toolchain.cmake -DPLATFORM=OS64 -DENABLE_BITCODE=OFF -DENABLE_ARC=ON -DMACOSX_BUNDLE_GUI_IDENTIFIER=com.fl.raw2dng -DMACOSX_BUNDLE_BUNDLE_NAME=MyApp -DIOS_BUILD=1